### ISSUE TITLE
Métodos Python

### ISSUE THREAD

**Issue by EMILSEGUDINO** [Evelyn-Masin/PROYECTO-INTEGRADOR-ISPC-2023#5]
- [] Metodo Insert Python
- [] Mètodo Select Python
- [] Verificar trabajo colaborativo

**Comment by EMILSEGUDINO** [comment]
Gente, me esta costando conectarlo con la base

**Comment by Evelyn-Masin** [comment]
Me pasa lo mismo, no estoy pudiendo conectar
