### ISSUE TITLE
Ley 25326

### ISSUE THREAD

**Issue by EMILSEGUDINO** [Evelyn-Masin/PROYECTO-INTEGRADOR-ISPC-2023#6]
- [] Leer Ley 25326
- [] Radacciòn de punto 3
- [] subir a repositorio

**Comment by Evelyn-Masin** [comment]
Documento de Ley 25326 adjunto.- 

Subido a repositorio. 
[Proyecto integrador ISPC 2023- Desarrollo Ley 25326.docx](https://github.com/Evelyn-Masin/PROYECTO-INTEGRADOR-ISPC-2023/files/11717035/Proyecto.integrador.ISPC.2023-.Desarrollo.Ley.25326.docx)
